<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8">
		<title><?php echo $title; ?></title>
		
		<!-- CSS -->
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"><!-- У меня сомнения по поводу разрешения на использование этого -->
		<link rel="stylesheet" type="text/css" href="media/style.css">
		
		<!-- Скрипты -->
		<script src="media/script.js" defer></script>
	</head>
	<body>
		<?php include( 'templates/parts/menu.phtml' ); ?>